AntraTraining/MovieWebsite/Models/ErrorViewModel.cs
namespace MovieWebsite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AntraTraining/MovieWebsite/Controllers/AccountController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Exceptions;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MovieWebsite.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }
        [HttpGet]
        public IActionResult Register()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterModel model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            //Save info in user table
            try
            {
                var user = await _accountService.RegisterUser(model);
            }
            catch(ConflictException)
            {
                throw;
            }
            
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                var user = await _accountService.LoginUser(model.Email, model.Password);
                if(user != null)
                {

                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.GivenName, user.FirstName),
                        new Claim(ClaimTypes.Surname, user.LastName),
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.DateOfBirth, user.DateOfBirth.ToShortDateString()),
                        
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));



                    return LocalRedirect("~/");

                }
                
            }
            catch (Exception)
            {
                return View();
                throw;
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

AntraTraining/MovieWebsite/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieWebsite.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var castDetails = await _castService.GetCastDetails(id);
            return View(castDetails);
        }
    }
}

AntraTraining/MovieWebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MovieWebsite.Models;
using Infrastructure.Services;
using ApplicationCore.Contracts.Services;

namespace MovieWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieService _movieService;
        public HomeController(ILogger<HomeController> logger, IMovieService movieService)
        {
            _logger = logger;
            _movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            //var movieService = new MovieService();
            var movieCards = await _movieService.GetTop30GrossingMovies();
            // passing the data from Controller action method to View
            return View(movieCards);
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        // https://localhost:7273/home/TopRatedMovies
        public IActionResult TopRatedMovies()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AntraTraining/MovieWebsite/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;

namespace MovieWebsite.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id)
        {
            //Data
            //Remote Database
            //CPU bound operation => PI, Loan calculations
            //I/O bound operation => Database calls, file, images, videos. Async preferred

            //External thread speed dependencies:
            //Network, SQL server Query, Server Memory, (etc)
            //T1 is just waiting so it's available for a new request
            //Basically multithreading
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }
        [HttpGet]
        public async Task<IActionResult> Genres(int id, int pageSize=30, int pageNumber =1)
        {

            var pagedMovies = await _movieService.GetMoviesByGenrePagination(id, pageSize, pageNumber);

            return View("PagedMovies", pagedMovies);
        }
    }
}

AntraTraining/MovieWebsite/Controllers/UserController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MovieWebsite.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        //[HttpGet]
        // public IActionResult Details(int id)
        // {
        //     return View();
        // }
        // 
        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            //Get user data from cookie
            //var data = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];
            //var isLoggedIn = this.HttpContext.User.Identity.IsAuthenticated;
            //if(!isLoggedIn)
            //{

            //}

            var userId = Convert.ToInt32( this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Favorites(int userId)
        {
            var movies = _userService.GetAllFavorites(userId);
            return View();
        }
    }
}

AntraTraining/MovieWebsite/Views/Cast/Details.cshtml
@model ApplicationCore.Models.CastDetailsModel

<div class="containcolor" >

  <div class="row">
    <div class="col">
      <h1>@Model.Name</h1>
      
      <img src="@Model.ProfilePath" width="200" />
    </div>
        

  </div>
  <div class="row">
      <h2><b>Featured Movies</b></h2>
        @foreach(var movie in Model.MoviesOfCast)
        {
                <div style="width:100px">
                
                <partial name="_MovieCardPartial" model="movie"/> 
                
                </div>
        }
  </div>
</div>

AntraTraining/MovieWebsite/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardModel>

@{
    ViewData["Title"] = "Home Page";

}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movieCard in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2" >
                   <partial name="_MovieCardPartial" model="movieCard"  />
                </div>
            }
        </div>
    </div>
</div>

AntraTraining/MovieWebsite/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel


<div class="containcolor" >
  <div class="row" style="background-image:url(@Model.BackdropUrl); background-size:cover;background-blend-mode:darken">
    <div class="col">
      <img src="@Model.PosterUrl" width="200" />
    </div>
    <div class="col my-4">
      <h3 style="color:white">@Model.Title</h3>
      <h6 style="font-size:smaller; color:gray">@Model.Tagline</h6>
      <h5 style="color:white">@Model.RunTime m | @Model.ReleaseDate.Value.Year 
          @foreach(var genre in Model.Genres)
           {<span class="badge bg-black" style="font-size:11px">@genre.Name </span>
           }
      </h5>
      <h6 style="font-size:smaller; color:white">@Model.Overview</h6>

    </div>
    <div class="col ms-lg-auto my-5">

      <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#reviewModal">REVIEW</button>
      <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#buyModal">BUY</button>

    </div>
  </div>
  <br />
  <br />
  <br />
  @*Movie Facts*@
  <div class="row start-0" >
      <div class="col-5">
          <ul class="list-group" style="list-style:none">
              <li>
                  <h3>MOVIE FACTS</h3>
                 <ul class="list-group" style="font-size:10px">
                      <li class="list-group-item" >Release Date: <span class="badge bg-black">@Model.ReleaseDate.Value.Date</span></li>
                      <li class="list-group-item" >Run Time: <span class="badge bg-black">@Model.RunTime m</span></li>
                      <li class="list-group-item" >Box Office: <span class="badge bg-black">$@Model.Revenue m</span></li>
                      <li class="list-group-item" >Budget: <span class="badge bg-black">$@Model.Budget m</span></li>
              
                 </ul>
              </li>
              <li>
                  <h3>TRAILERS</h3>
                  @foreach(var trailer in @Model.Trailers)
                    {
                        <b><a href="@trailer.TrailerUrl" style="text-decoration:none; font-palette:dark">@trailer.Name</a></b><br />
                    }
                </li>
          </ul>
      </div>
  @*Cast*@
      <div class="col">
          <h3>CAST</h3>
          <ul class="list-group" style="font-size:15px; list-style:none">
              @foreach(var cast in Model.Casts)
                {
                    <li class="list-group-item"><a asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id"><b> @cast.Name</b></a> <span><b>@cast.Character</b></span></li>
                }
          </ul>
        </div>
  </div>
</div>

@*Buy modal*@
<div class="modal fade" id="buyModal" tabindex="-1" aria-labelledby="BuyMovie" aria-hidden="true" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
          <span>Confirm purchase of @Model.Title for $@Model.Price</span>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    
      <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
           <button type="submit" class="btn btn-primary">Buy</button>
      </div>
        </div>
    </div>

</div>

@*Review modal*@
<div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="ReviewMovie" aria-hidden="true" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <label class="col-form-label">Rating:</label>
        <select class="form-select form-select-sm" aria-label=".form-select-sm example">
          <option selected>Select</option>
          <option value="10">10</option>
          <option value="9">9</option>
          <option value="8">8</option>
          <option value="7">7</option>
          <option value="6">6</option>
          <option value="5">5</option>
          <option value="4">4</option>
          <option value="3">3</option>
          <option value="2">2</option>
          <option value="1">1</option>
</select>
<label class="col-form-label">Review: </label>
<textarea class="form-control"></textarea>


      </div>
      <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
           <button type="submit" class="btn btn-primary">Submit</button>
      </div>
        </div>
    </div>

</div>

AntraTraining/MovieWebsite/Views/Movies/PagedMovies.cshtml
@model ApplicationCore.Models.PagedResult<ApplicationCore.Models.MovieCardModel>
<div class="rounded">
    <div class="container-fluid">
        <div class="row">
    @foreach(var movie in Model.Data)
    {
        <div class="col-6 col-lg-3 col-sm-4 col-xl-2" >
        <partial name="_MovieCardPartial" model="movie"/>
        </div>
    }
        </div>
    </div>
</div>
    <nav aria-label="Page navigation example">

            <ul class="pagination">

            @for(int i = 1; i <= Model.TotalPages; i++)
            {
                    <li class="page-item"><a class="page-link" asp-controller="Movies" asp-action="Genres" asp-route-pageNumber="@i">@i</a></li>
            }
            </ul>

    </nav>

AntraTraining/MovieWebsite/Views/Shared/_DetailsLoginInfo.cshtml
@using MovieWebsite.Services
@inject ICurrentUser currentUser

@if(currentUser.IsAuthenticated)
{
    
}

AntraTraining/MovieWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">Jorge's Movie Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            
                                <a class="text-light nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"data-bs-toggle="dropdown" aria-expanded="false">Genres</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="1" >Adventure</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="2" >Fantasy</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="3" >Animation</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="4" >Drama</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="5" >Horror</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="6" >Action</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="7" >Comedy</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="8" >History</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="9" >Western</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="10" >Thriller</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="11" >Crime</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="12" >Documentary</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="13" >Science Fiction</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="14" >Mystery</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="15" >Music</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="16" >Romance</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="17" >Family</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="18" >War</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="19" >Foreign</a></li>
                                   <li><a class="dropdown-item" asp-area="" asp-controller="Movies" asp-action="Genres" asp-route-id="20" >TV Movie</a></li>
                                </ul>
                                
                          
                        
                    </ul>
                </div>
                <partial name="_LoginInfoPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                           
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AntraTraining/MovieWebsite/Views/Shared/_LoginInfoPartial.cshtml
@using MovieWebsite.Services
@*if user is authenticated
show first name + last name
dropdown for links
1. movies (purchased movues) -> user/purchases
2. favorites -> user.favorites
3. account info -> user/edit
4. logout -> logout and redirect to login page


if else

show links
1. Register -> account/register
2. Login -> account/login
.
*@
    
@*<div class="text-end">
    <a class="btn btn-outline-dark me-2" asp-controller="Account" asp-action="Login">Login</a>
    <a class="btn btn-outline-dark me-2" asp-controller="Account" asp-action="Register">Register</a>
</div>*@

@inject ICurrentUser currentUser

@if(currentUser.IsAuthenticated)
{
    <div class="text-end">
        <ul class="nav">
            <li class="nav-item dropdown text-capitalize">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">@currentUser.FullName</a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><a class="dropdown-item" asp-controller="User" asp-action="Purchases">Library</a></li>
                <li><a class="dropdown-item" asp-controller="User" asp-action="Favorites" asp-route-userId="@currentUser.userId">Favorites</a></li>
                <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">Account</a></li>
                <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
              </ul>
            </li>
        </ul>
    </div>
}
else
{
<div class="text-end">
    <a class="btn btn-outline-light me-2" asp-controller="Account" asp-action="Login" >  Login </a>
    <a class="btn btn-outline-light me-2" asp-controller="Account" asp-action="Register" > Register </a>
</div>
}

AntraTraining/MovieWebsite/Views/Shared/_MovieCardPartial.cshtml
@model ApplicationCore.Models.MovieCardModel

<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title">
    </a>

</div>

AntraTraining/MovieWebsite/Views/User/Favorites.cshtml
@model List<ApplicationCore.Models.MovieCardModel>

@if(Model == null)
{
    <div class="mx-auto" width="200px">You don't have any favorite movies</div>
}
else
{
       @foreach(var movie in Model)
        {
                <div style="width:100px">
                
                <partial name="_MovieCardPartial" model="movie"/> 
                
                </div>
        }
}